Add missing grype detailed check

diff --git a/.github/workflows/reusable-factory.yaml b/.github/workflows/reusable-factory.yaml
--- a/.github/workflows/reusable-factory.yaml
+++ b/.github/workflows/reusable-factory.yaml
@@ -269,6 +269,17 @@ jobs:
           add-cpes-if-none: true
           only-fixed: true
           fail-build: false
+      - name: Grype detailed check
+        if: inputs.grype
+        run: |
+          jq -r '.matches[] | select(.vulnerability.severity == "Critical") | "\(.vulnerability.id) \t \(.artifact.name) \(.artifact.version) -> \(.artifact.locations[]?.path // "no-path")"' "${{ steps.grype.outputs.json }}" | tee grype-critical.txt
+
+          if [[ $(wc -l < grype-critical.txt) -gt 0 ]]; then
+            echo "Critical vulnerabilities found in the image. Failing the build."
+            exit 1
+          else
+            echo "No critical vulnerabilities found in the image."
+          fi
 
       - name: Run Trivy security scan
         if: inputs.trivy
